parameters:
  connentionParams:
    url: mysql://root:root@localhost/image-minify-api
  configPath: %basePath%/config
services:
  minify:
    class: IngoWalther\ImageMinifyApi\Minify\Minify
    arguments: [@fileHandler]
    calls:
      - [addCompressor, [@mozJpegCompressor]]
      - [addCompressor, [@pngquantCompressor]]
  mozJpegCompressor:
    class: IngoWalther\ImageMinifyApi\Compressor\MozJpegCompressor
  pngquantCompressor:
    class: IngoWalther\ImageMinifyApi\Compressor\PngquantCompressor
  fileHandler:
    class: IngoWalther\ImageMinifyApi\File\FileHandler
  randomStringGenerator:
    class: IngoWalther\ImageMinifyApi\Security\RandomStringGenerator
  apiKeyCheck:
    class: IngoWalther\ImageMinifyApi\Security\ApiKeyCheck
    arguments: [@userRepository]
  apiKeyGenerator:
    class: IngoWalther\ImageMinifyApi\Security\ApiKeyGenerator
    arguments: [@userRepository, @randomStringGenerator]
  userRepository:
    class: IngoWalther\ImageMinifyApi\Database\UserRepository
    arguments: [@dbConnection]
  dbConfig:
    class: Doctrine\DBAL\Configuration
  dbConnection:
    factory_class: Doctrine\DBAL\DriverManager
    factory_method: getConnection
    arguments: [%connentionParams%, @dbConfig]

  console:
    class: Symfony\Component\Console\Application
    calls:
      - [add, [@addUserCommand]]
      - [add, [@listUserCommand]]
      - [add, [@setupCommand]]
  addUserCommand:
    class: IngoWalther\ImageMinifyApi\Command\AddUserCommand
    calls:
      - [setApiKeyGenerator, [@apiKeyGenerator]]
  listUserCommand:
    class: IngoWalther\ImageMinifyApi\Command\ListUserCommand
    calls:
      - [setUserRepository, [@userRepository]]
  setupCommand:
    class: IngoWalther\ImageMinifyApi\Command\SetupCommand
    calls:
      - [setConnection, [@dbConnection]]
      - [setConfigPath, [%configPath%]]
